/**
 * Résout une icône lucide-react par son nom (chaîne).
 * Permet à site-content.ts de référencer les icônes par string ("Globe",
 * "Phone"...) sans imposer d'imports React au fichier de config.
 *
 * Liste complète : https://lucide.dev/icons/
 */

import {
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Car,
  CarFront,
  CircleDollarSign,
  Clock,
  Code,
  Coins,
  CreditCard,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Hammer,
  HandHelping,
  HeartHandshake,
  Heart,
  HelpCircle,
  Home,
  Landmark,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Palette,
  Paintbrush,
  PiggyBank,
  Phone,
  Scale,
  Search,
  Settings2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  UserCheck,
  Users,
  Utensils,
  Wine,
  Wrench,
  Youtube,
  Video,
  type LucideIcon,
} from 'lucide-react'

const iconMap: Record<string, LucideIcon> = {
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarRange,
  Car,
  CarFront,
  CircleDollarSign,
  Clock,
  Code,
  Coins,
  CreditCard,
  FileText,
  Gift,
  Globe,
  GraduationCap,
  HandCoins,
  Hammer,
  HandHelping,
  Heart,
  HeartHandshake,
  Home,
  Landmark,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Palette,
  Paintbrush,
  Phone,
  PiggyBank,
  Scale,
  Search,
  Settings2,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  UserCheck,
  Users,
  Utensils,
  Video,
  Wine,
  Wrench,
  Youtube,
}

export function getIcon(name?: string): LucideIcon {
  if (!name) return HelpCircle
  return iconMap[name] ?? HelpCircle
}

export type IconName = keyof typeof iconMap
